# Generated by Django 4.1.3 on 2022-11-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_practicearea_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicearea',
            name='learnmore',
            field=models.URLField(blank=True, null=True),
        ),
    ]
