# Generated by Django 4.1.3 on 2022-11-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_user_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='collapseOne',
            field=models.CharField(default='#collapse', max_length=100),
        ),
    ]
