# Generated by Django 4.1.3 on 2022-11-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_question_collapseone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='collapseOne',
        ),
        migrations.AddField(
            model_name='question',
            name='collapse',
            field=models.CharField(default='#collapse', max_length=100),
        ),
    ]
