# Generated by Django 4.1.3 on 2022-12-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_question_question_id_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='collapse',
            field=models.CharField(default='#collapse', max_length=60),
        ),
    ]
